# Generated by Django 2.2.4 on 2019-10-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='resultado',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='recomendacion',
            field=models.CharField(max_length=300),
        ),
    ]
